# Generated by Django 5.0.2 on 2024-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Going_out', 'Going Out'), ('Health', 'Health'), ('Groceries', 'Groceries'), ('Holiday', 'Holiday'), ('Children', 'Children'), ('Education', 'Education'), ('Gifts', 'Gifts'), ('Shopping', 'Shopping'), ('Sports', 'Sports'), ('Leisure', 'Leisure'), ('Savings', 'Savings')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Transfer', 'Transfer')], max_length=30, null=True),
        ),
    ]
