# Generated by Django 5.0.2 on 2024-02-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Going out', 'Going Out'), ('Health', 'Health'), ('Groceries', 'Groceries'), ('Holiday', 'Holiday'), ('Children', 'Children'), ('Education', 'Education'), ('Gifts', 'Gifts'), ('Shopping', 'Shopping'), ('Sports', 'Sports'), ('Leisure', 'Leisure'), ('Savings', 'Savings')], max_length=30),
        ),
    ]
